on:
  push:
    branches:
      - 'main' # Your master branch
env:
  IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/simple_web # feel free to edit to your project name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Publish Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
          ssh -tt root@${{ secrets.SSH_HOST }} "docker pull ${{ env.IMAGE_NAME }}:latest && docker run -d -p 3000:80 ${{ env.IMAGE_NAME }}:latest"
      - name: Cleanup
        run: rm -rf ~/.ssh